services:
  astro:
    image: node:22-alpine
    container_name: astro-app
    working_dir: /app
    command: npm run dev -- --host
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "4321:4321"

volumes:
  node_modules:
