# .github/workflows/deploy.yml

name: Audit, Build, and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  # Run the workflow every day at 5:00 AM UTC
  schedule:
    - cron: '0 5 * * *'

# Allow this job to clone the repo, commit fixes, and create a page deployment
permissions:
  contents: write
  pages: write
  id-token: write

# Define environment variables shared across all jobs in the workflow
env:
  NODE_VERSION: '20'

jobs:

  audit:
    runs-on: ubuntu-latest
    # This 'if' condition is crucial to prevent infinite loops.
    # It stops the job from running if the trigger was a commit made by this workflow.
    if: "!contains(github.event.head_commit.message, 'chore(security):')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Use the shared environment variable
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        id: audit
        run: npm audit
        continue-on-error: true # Continue even if vulnerabilities are found

      - name: Run npm audit fix if vulnerabilities were found
        if: steps.audit.outcome == 'failure'
        run: npm audit fix

      - name: Commit and push changes
        if: steps.audit.outcome == 'failure'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # The commit message that will be used for the fix.
          commit_message: 'chore(security): Apply automatic npm audit fix'
          branch: main
          file_pattern: package.json package-lock.json

  build:
    needs: audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
